services:
  - type: web
    name: projet-roulot-lilia
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/roulot_lilia/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
